Merged V3.3 to V3.3-BUG-FIX    20883: ALF-3604: Fix PersonTest    20881: Merged PATCHES/V3.2.r to V3.3       20880: ALF-3264: Fix up handling of default namespace. Workaround to JXPATH-61    20878: Merged V2.2 to V3.3       20474: Fix for ALF-1362 - encode group identifiers when used inside embedded param tags       20621: Fix for reopened ALF-1362 - UnknownAuthorityException when viewing/editing/deleting a user group with html entities in it's name    20874: Merged HEAD to V3.3       20873: ALF-3604: Correct case-sensitivity issues in LDAP sync          - User names are now brought in line with the case of the LDAP directory during sync (in case the UID attribute is case sensitive)          - User names are now compared according to Alfresco's case sensitivity setting          - Group name comparisions are still case sensitive          - Added unit test to ensure correct behaviour    20868: Merged PATCHES/V3.2.r to V3.3       20832: ALF-3264: XForms 'schema evolution': Remove nodes from XForms instance document with XPaths that don't occur in prototype document    20867: Merged PATCHES/V3.2.r to V3.3 (RECORD ONLY)       20833: Incremented version label       20688: Incremented version label       20687: Merged V3.3 to PATCHES/V3.2.r          20398: Fixed ALF-2890: Upgrade removes content if transaction retries are triggered             - Setting ContentData that was derived outside of the current transaction opened up a window               for the post-rollback code to delete the underlying binary. The binaries are only registered               for writers fetched via the ContentService now; the low-level DAO no longer does management               because it can't assume that a new content URL indicates a new underlying binary.             - The contentUrlConverter was creating new URLs and thus the low-level DAO cleaned up               live content when retrying collisions took place. The cleanup is no longer on the stack               for the patch.             - Removes the ALF-558 changes around ContentData.reference()          20590: Fixed ALF-3189: Oracle/DB2/SQLServer/PostgreSQL are missing indexes to support many FK constraints             - Reverses rev 17421             - Added patchy bits to post-create script and declared patch             - Patch only applies to *new* installations from 3.2.0 onwards (schema 3007 to 3400)       20686: ALF-3259: Merged HEAD to PATCHES/V3.2.r          19784: Fix for CIFS/CheckInOut.exe save of working copy breaks lock on original file. ALF-2028.    20866: Merged PATCHES/V3.2.1 to V3.3 (RECORD ONLY)       20840: Incremented version label       20839: ALF-3691: Merged V3.3-BUG-FIX to PATCHES/V3.2.1          20307: VersionStore - minor fixes if running deprecated V1             - warn in startup log             - do not execute migration cleanup          20367: ALF-2829: Avoid reading entire result set into memory in FixNameCrcValuesPatch          20368: Work-around for ALF-2366: patch.updateDmPermissions takes too long to complete             - this patch may now be deferred until 3.4 using the sample context (DM will use old permissions and AVM new as it did in 2.2.x)             - this is only supported upgrading direct to 3.2.1.x          20370: Version Migrator (ALF-1000) - use common batch processor to enable multiple workers          20373: Version Migrator (ALF-1000) - resolve runtime conflict (w/ r20334)          20387: Version Migrator (ALF-1000) - approx x3 boost (policies ignore version2 store)          20431: Version Migrator (ALF-1000) - migrate 1st batch independently       20738:ALF-3617: Merged V3.3-BUG-FIX to PATCHES/V3.2.1          20438: ALF-479: Merged DEV/BELARUS/V3.2-2010_01_11 to DEV/V3.3-BUG-FIX             18448: ETHREEOH-4044: External Authentication Subsystem does not perform user mapping for WebDAV requests                The changes listed in the bug comments have been made (and corrected).       20728: Incremented version label       20727: ALF-3617: Merged HEAD to PATCHES/V3.2.1          20616: ALF-2265: Share 'Uber Filter' part 2             - WebScriptNTLMAuthenticationFilter detached from its superclass and renamed to WebScriptSSOAuthenticationFilter             - Now the filter simply chains to the downstream authentication filter rather than call its superclass             - This means the same filter can be used for Kerberos-protected webscripts as well as NTLM             - Wired globalAuthenticationFilter behind webscriptAuthenticationFilter in the filter chain in web.xml             - Configured webscriptAuthenticationFilter for Kerberos subsystem       20612: Incremented version label       20610: Merged V3.3 to PATCHES/V3.2.1          20590: Fixed ALF-3189: Oracle/DB2/SQLServer/PostgreSQL are missing indexes to support many FK constraints            - Reverses rev 17421            - Added patchy bits to post-create script and declared patch            - Patch only applies to *new* installations from 3.2.0 onwards (schema 3007 to 3501)       20403: Merged V3.3 to PATCHES/V3.2.1          20398: Fixed ALF-2890: Upgrade removes content if transaction retries are triggered             - Setting ContentData that was derived outside of the current transaction opened up a window for the post-rollback code to delete the underlying binary. The binaries are only registered for writers fetched via the ContentService now; the low-level DAO no longer does management because it can't assume that a new content URL indicates a new underlying binary.             - The contentUrlConverter was creating new URLs and thus the low-level DAO cleaned up live content when retrying collisions took place. The cleanup is no longer on the stack for the patch.             - Removes the ALF-558 changes around ContentData.reference()       20391: Incremented version label       20390: ALF-2966: Merged DEV/V3.3-BUG-FIX to PATCHES/V3.2.1          20388: Merged BRANCHES/DEV/BELARUS/HEAD-2010_04_28 to BRANCHES/DEV/V3.3-BUG-FIX:             20372: ALF-897: It is impossible to create content when default value selected in ContentHeadlineBackground field for intranet_rssi_landing_template web-form (also fixes ALF-2798 & ALF-791)       20371: ALF-2861: Merged V3.2 to PATCHES/V3.2.1          20028: Reverted (and fixed line endings) of log4j.properties          20027: Merged BRANCHES/V3.1 to BRANCHES/V3.2:             19983: Changes for ALF-2545: Cannot upgrade from 2.1.2a (b 209) to the 3.1.2 (.a3 458) on Oracle             20008: ALF-2351: Oracle upgrade scripts need enhancements from 2.2SP7       20362: ALF-2883: Merged HEAD to V3.2.1          19750: Fix for ALF-2310: alfresco-mmt-3.3dev.jar shows NoClassDefFoundError: org/safehaus/uuid/UUIDGenerator       20359: Merged PATCHES/V3.2.0 to PATCHES/V3.2.1          20349: Merged V3.3 to PATCHES/V3.2.0             20346: ALF-2839: Node pre-loading generates needless resultset rows                - Added missing Criteria.list() call          20280: Fixed ALF-2839: Node pre-loading generates needless resultset rows             - Split Criteria query to retrieve properties and aspects separately          20272: Backports to help fix ALF-2839: Node pre-loading generates needless resultset rows             Merged BRANCHES/V3.2 to PATCHES/V3.2.0:                18490: Added cache for alf_content_data             Merged BRANCHES/DEV/V3.3-BUG-FIX to PATCHES/V3.2.0:                20231: Fixed ALF-2784: Degradation of performance between 3.1.1 and 3.2x (observed in JSF)          20266: Test reproduction of ALF-2839 failure: Node pre-loading generates needless resultset rows       20358: Increment version label       20343: Incremented version label       20342: Merged V3.3 to PATCHES/V3.2.1          20322: Fixed ALF-1998: contentStoreCleanerJob leads to foreign key exception             - Possible concurrent modification of alf_content_url.orphan_time led to false orphan detection             - Fixed queries to check for dereferencing AND use the indexed orphan_time column             - More robust use of EagerContentStoreCleaner: On eager cleanup, ensure that URLs are deleted             - Added optimistic lock checks on updates and deletes of alf_content_url    20864: Merged PATCHES/V3.2.0 to V3.3 (RECORD ONLY)       20750: Merged V3.3 to PATCHES/V3.2.0          20590: Fixed ALF-3189: Oracle/DB2/SQLServer/PostgreSQL are missing indexes to support many FK constraints             - Reverses rev 17421             - Added patchy bits to post-create script and declared patch             - Patch only applies to *new* installations from 3.2.0 onwards (schema 3007 to 3400)       20748: Incremented version label       20745: ALF-3639: Merged V3.2 to PATCHES/V3.2.0          18363: WCM clustering - ETHREEOH-3962 (duplicate root node entry)    20863: Merged PATCHES/V3.1.2 to V3.3       20830: ALF-934: Another go at making External Access Servlet reset JSF view state for the document it is requesting       20701: ALF-3203: Guarantee a deterministic initialization sequence for WebClientConfigBootstrap (PARTIAL - Needs Surf fix)    20861: Merged PATCHES/V3.2.1 to V3.3 (RECORD ONLY)       20831: Incremented version label       20702: Incremented version label       20681: ALF-3109: Merged V3.2 to PATCHES/V3.1.2          16933: Fix ETHREEOH-1788 - Bootstrap fails due to disabled-avm-indexing-context.xml       20680: ALF-3109: Merged V3.2 to PATCHES/V3.1.2          16714: WCM/AVM fixes             - ETHREEOH-2697 - file system likely to get full with avm lucene directories for unindexed WCM store             - ETHREEOH-1847 - re-starting cluster node may show non-staging WCM store indexes out-of-date (although not indexed)       20611: Incremented version label       20538: ALF-3117: Merged HEAD to PATCHES/V3.1.2          17099: Build Fix for failing permission test (missing flush in DAO)       20535: ALF-3141: Merged V3.2 to PATCHES/V3.1.2          17441: Build fix: Fix AVM permission inheritance to match DM and fix common permission dao component       20534: Incremented version label       20533: ALF-3117: Merged DEV/V3.3-BUG-FIX to PATCHES/V3.1.2          20368: Work-around for ALF-2366: patch.updateDmPermissions takes too long to complete             - this patch may now be deferred until 3.4 using the sample context (DM will use old permissions and AVM new as it did in 2.2.x)             - this is only supported upgrading direct to 3.3.1       20532: ALF-3117: Merged V3.2 to PATCHES/V3.1.2          17076: Improvements for ETHREEOH-2153: patch.updateDmPermissions takes too long to complete       20531: ALF-3141: Merged V3.2 to PATCHES/V3.1.2          17419: Fix for ETHREEOH-3296: Enterprise 3.X / Permissions Error When Cut & Paste on Sub-Folder       20516: Incremented version label       20515: ALF-3109: Merged V3.2 to PATCHES/V3.1.2          18363: WCM clustering - ETHREEOH-3962 (duplicate root node entry)    20860: Merged V3.1 to V3.3       19424: Fix bug in permission evaluation time reporting    20859: Merged V3.1 to V3.3 (RECORD ONLY)       20599: Incremented version label       20596: ALF-3184: Merged V3.3-BUGFIX to V3.1A          20307: VersionStore - minor fixes if running deprecated V1             - warn in startup log             - do not execute migration cleanup          20370: Version Migrator (ALF-1000) - use common batch processor to enable multiple workers          20373: Version Migrator (ALF-1000) - resolve runtime conflict (w/ r20334)          20387: Version Migrator (ALF-1000) - approx x3 boost (policies ignore version2 store)          20431: Version Migrator (ALF-1000) - migrate 1st batch independently       20591: ALF-3184: Merged V3.2 to V3.1A (partial)          19507: ALF-955: deletion of dynamic custom model             - ignore policies/behaviours for node archive store (reviewed w/ DH)          19553: Follow-on to r19507 (ALF-955) - fix testAutoRemovalOfVersionHistory       20577: ALF-3184: Ported BatchProcessor to V3.1A in preparation for VersionMigrator port       19426: Fix for eclipse build path: Part 2       19425: Fix for eclipse build path       19305: Merged V3.2 to V3.1 ('cause you never know!)          19304: Removed static (singleton) usage of CacheFactory       18996: MOB-388: Fixed copying of properties       18919: CopyServiceChildAssocsFix on 3.1       18566: Removed svn:mergeinfo       18428: Backport of r14260:  fixed code typo which cased a ClassCastException with multiple pooled actors.       18424: Updated version label to 3.1.2.1       17861: Merge 2.2 to 3.1:          17803: Re-use open files for the same session/process id so that writes on each file handle go to the same file. ETWOTWO-1250. (Record-only)       17843: Re-use open files for the same session/process id so that writes on each file handle go to the same file. Port of ETWOTWO-1250.       17842: Missing file from previous checkin.       17839: Rewrite the rename file logic to handle MS Office file rename patterns. ETHREEOH-1951.       17359: Fix for CIFS/Kerberos/SPNEGO logon problem with Win2008/Win7 client. ETHREEOH-3225.       17193: ETHREEOH-3112: Issue for adding / deleting non-English files          Appropriate encoding for non English symbols was added.          Ported from V3.2.       17181: Fixed typo on --record-only       17130: Fix for cannot delete file via CIFS that has a thumbnail associated with it. ETHREEOH-3143 and ETHREEOH-3115.    20858: Merged V2.2 to V3.3       18568: (RECORD ONLY) Fix for CIFS SendTo->Compressed Folder 'not enough space' error. ETWOTWO-596.       Ported latest v3 repo filesystem rename logic to v2, should fix a few other issues too.       17803: (RECORD ONLY) Re-use open files for the same session/process id so that writes on each file handle go to the same file. ETWOTWO-1250.    20857: Merged V2.2 to V3.3       20504: Merged DEV/BELARUS/V2.2-2010_02_03 to V2.2          19346: ALF-1358: Deleting space with "execute a script" rule fails             - The invocation of the RuleServiceImpl.getRule() was added on the ruleNodeRef to get updated associations of the last one. (???)       20476: Fix for ALF-1863: Advanced Search does not work with custom type of type d:int with a constraint of type LIST       20475: Merged DEV/TEMPORARY to V2.2          20375: ALF-1830: Manage Task UI for Pooled Tasks: don't show Reject/Accept if user hasn't taken ownership       20472: (RECORD ONLY) ALF-1841: Merged DEV/BELARUS/V2.2-2009_12_01 to V2.2 (with corrections)          17865: ETWOTWO-935: Regression: readOnly settings do not work in 2.2 causing bootstrap to fail             The check on current mode is read only was added into AbstractLuceneIndexerAndSearcherFactory and  AlfrescoJobExecutorThread classes.       20068: Merged BRANCHES/DEV/BELARUS/V2.2-2010_02_03 to BRANCHES/V2.2:          19326: ALF-1932: ALF-1358 Deleting space with "execute a script" rule fails: Unit Test move to RuleServiceImplTest.       19670: Fix for ALF-1788: Renamed Category not usable in Query          - renaming a category in the admin console now also renames the association and changes the PATH by which the category is known.       19093: Fix ALF-1791          - added unit test       19055: Fix compile error introduced during pervious merge       19048: Merge DEV/BELARUS/V2.2-2010_02_03 to V2.2          19014 : ALF-883: Rule is not triggered for a item which is restored from the bin       19045: Merge DEV/V2.1SP7 to V2.2          12225 : ETWOONE-74 (Authentication tickets expire after set time, but would be more useful to have them expire after an inactivity timeout.)       18958: Merged BELARUS/V2.2-2010_02_03 18850 Fixed ALF-1358: Deleting space with "execute a script" rule fails          - Merged the fix only.  The unit test belongs to the RuleService.       18918: (RECORD ONLY) Fixed backward compatibility of CopyServiceChildAssocsFix module       18759: (RECORD ONLY) Merged DEV/BELARUS/V2.2-2010_02_03 to V2.2          18553: ResultSet closing was added to methods          This was fixed separately in V3.2; port forward selectively       18561: (RECORD ONLY) Merged DEV to V2.2          18552: Fix ETWOTWO-1389: Issues with ACL upgrade script for Oracle           (DH: Removed commented-out SQL statements)       16304: (RECORD ONLY) ETWOONE-335: Parallel Review does not store Priority and Due Date set at task creation          1. Appropriate changes have been made in parallelreview_group_processdefinition.xml and parallelreview_processdefinition.xml files.          2. Redeploy flag is kept with false value by default in the workflow-context.xml.sample file.          3. A sorting of the list of workflow definitions by name has been already applied in all branches according to ETWOTWO-302 issue fix.    20855: Fix for ALF-3690. Unable to FTP files into Share site documentLibrary folder.       This fix corrects what it essentially a typo. The dictionaryService was injected twice into the CreateNodeRuleTrigger bean, rather than the dictionaryService and the ruleService.    20853: Merged V2.2 to V3.3 (RECORD ONLY)       20459: Build fix - don't try to delete the guest user in PersonTest       20411: Merged BRANCHES/V3.1 to BRANCHES/V2.2: (for ALF-2628)          14863: (RECORD ONLY) Fixed ETHREEOH-2223: Oracle version-specific schema update failure in upgrading from 2.1A build to       20383: Merged V3.2 to V2.2 (Fixes duplicate ALF-1359)          16731: ETHREEOH-2411: Error message appears when trying to create advanced workflow with long description       19303: Updated version to 2.2.7       17811: Updated version to 2.2.6       17433: Merged V3.1 to V2.2          15894: Fix ETHREEOH-2416 and ALFCOM-3300: Duplicate name exceptions not being trapped correctly             Fixes ETWOTWO-1261       15869: Port of desktop action client side EXE fixes from v3.x. ETWOTWO-1374.    20849: (RECORD ONLY) Merged V3.3-BUG-FIX to V3.3       20847: Fixes Recent Documents and My Tasks localisation issues: ALF-2021 & adds an FTL friendly medium length date format property