The last part of ALF-2175 issue is complete. We have ported 3.3 create script for DB2 and added required “qname-insert-SqlMap.xml”.
NOTES: In addition we have to modified org.alfresco.ibatis.SerializableTypeHandlerCallback class to allow bootstrap on db2. The following error was 
occurred:

Cause: com.ibm.db2.jcc.b.SqlException: DB2 SQL error: SQLCODE: -301, SQLSTATE: 07006, SQLERRMC: 9
                at org.springframework.jdbc.support.SQLErrorCodeSQLExceptionTranslator.doTranslate(SQLErrorCodeSQLExceptionTranslator.java:233)
                at org.springframework.jdbc.support.AbstractFallbackSQLExceptionTranslator.translate(AbstractFallbackSQLExceptionTranslator.java:72)
                at org.springframework.orm.ibatis.SqlMapClientTemplate.execute(SqlMapClientTemplate.java:203)
                at org.springframework.orm.ibatis.SqlMapClientTemplate.insert(SqlMapClientTemplate.java:364)
                at org.alfresco.repo.domain.avm.ibatis.AVMStoreDAOImpl.insertStorePropertyEntity(AVMStoreDAOImpl.java:122) 

From IBM site we’ve found the detailed description of this problem : 
ERROR:                 07006 
MESSAGE:           An input host variable cannot be used, because of its data type.

This relates to “serializable_value” parameter in “insert_AVMStoreProperty_AutoIncrement” sql statement and the following snippet of code from 
SerializableTypeHandlerCallback cause it:

public void setParameter(ParameterSetter setter, Object parameter) throws SQLException
    {
        if (parameter == null)
        {
            setter.setNull(Types.LONGVARBINARY);
        }
…..

We suggest change it as below:

public void setParameter(ParameterSetter setter, Object parameter) throws SQLException
    {
        if (parameter == null)
        {
            setter.setNull(Types.BLOB);
        }
…..

We’ve tried only clean install and it was completed successfully. Upgrade is unavailable because of the same error on alfresco 3.2 bootstrap.