The iBatis migration for Oracle is completed but we have faced some problems that we would like to describe for further approve/reject.
1. File avm-common-SqlMap.xml <update id="update_AVMNode". This statement was not working on Oracle because it contains the same 
column name (lastModifier) twice. I have deleted duplication.
2. File avm-common-SqlMap.xml <select id="select_AVMNodes_orphans" and <select id="select_AVMNodes_layeredDirectories". Both this statement 
are incorrect for Oracle dialect because in where clause they contains “false, true” words. There is no Boolean type in Oracle so we 
decide to move this statement to dialect specific avm-insert-SqlMap.xml with appropriate modification for Oracle.
3. The last problem was occurred when avm store (sitestore) was bootstrapped. On store bootstrap it was assigned some properties (such as 
creator, created). On the moment of properties creation the appropriate qname was not already exists in database so the qname was created first. Then 
the id of newly created qname was passed to “insert_AVMStoreProperty” as qname_id parameter. But for some reason this statement execution faled with 
next stacktrace:
org.springframework.dao.DataIntegrityViolationException: SqlMapClient operation; SQL [];   
--- The error occurred in alfresco/ibatis/#resource.dialect#/avm-insert-SqlMap.xml.  
--- The error occurred while applying a parameter map.  
--- Check the alfresco.avm.insert_AVMStoreProperty-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: ORA-02291: integrity constraint (PAVELYUR.FK_AVM_SPROP_QNAME) violated - parent key not found
; nested exception is com.ibatis.common.jdbc.exception.NestedSQLException:   
--- The error occurred in alfresco/ibatis/#resource.dialect#/avm-insert-SqlMap.xml.  
--- The error occurred while applying a parameter map.  
--- Check the alfresco.avm.insert_AVMStoreProperty-InlineParameterMap.  
--- Check the statement (update failed).  
--- Cause: java.sql.SQLException: ORA-02291: integrity constraint (PAVELYUR.FK_AVM_SPROP_QNAME) violated - parent key not found

Next two links described problem in more details.
See http://forum.springsource.org/showthread.php?t=68672 , http://forum.springsource.org/archive/index.php/t-61208.html ; 

The solution right now is just not create the foreign key constraint fk_avm_sprop_qname for avm_store_properties tables.