update to org.codehaus.plexus 3.0, to avoid errors: Execution prepare-exploded-war of goal org.apache.maven.plugins:maven-war-plugin:2.4:exploded failed: An API incompatibility was encountered while executing org.apache.maven.plugins:maven-war-plugin:2.4:exploded: java.lang.NoSuchMethodError: org.codehaus.plexus.util.DirectoryScanner.setupMatchPatterns()V