Merged DEV to V4.0-BUG-FIX    33697: ALF-12691: Alfresco Explorer doesn't work: java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder       Shared library for WAS was fixed. commons-lang-2.6.jar is used.