Merged V3.4-BUG-FIX to V4.1-BUG-FIX    45756: ALF-14722: Repeat merge of V4.1-BUG-FIX to V3.4-BUG-FIX - previous merge in r43028 did not bring over all required changes    42902: Merged DEV to V4.1-BUG-FIX       42519: ALF-13588: Google Doc failed to authenticate after incorrect password being entered for google account          Add ability to unregister class behaviours.          Unregister googledocs behaviours when subsystem stops.    45948: Merged DEV/WABSON/V4.1-GOOGLEDOCS-BUG-FIX to DEV/V3.4-BUG_FIX       45898: ALF-17704 / ALF-16167: 'Edit Offline' checks out document in Google docs          - Edit in Google Docs action is now decoupled from Edit Offline action          - The checkout to Google Docs is only performed if a new parameter 'gdc' is set as a paramter when calling the action web script          - This paramter causes the web script to call a new method checkoutToGoogleDocs() on ScriptNode if the parameter is set          - The new method simply calls the existing checkout() method after setting a custom property on the transaction          - The Google Docs policies now check for the presence of this transaction property before sending the document to Google    45976: ALF-17876: Merged DEV to V3.4-BUG-FIX       45925: ALF-16992 : patch.fixAclInheritance is failing on sharedAclsThatDoNotInheritCorrectlyFromThePrimaryParent          Added a detection on cyclic loop for "inherits from" field.    46041: ALF-17877: Merged DEV to V3.4-BUG-FIX (with corrections)       46013: ALF-17662 : The deleted via Sharepoint document is not removed from Alfresco but hidden aspect is added for it       Documents marked with sys:hidden aspect should be invisible through SPP protocol and should be treated as nonexistent.    46054: ALF-17878 / ALF-17633 add alfresco-mmt.jar in the SDK distribution    46173: ALF-17879 / ALF-17806: Merged PATCHES/V3.4.10 to V3.4-BUG-FIX       46099: MNT-293: Merged V4.0-BUG-FIX to PATCHES/V3.4.10          37969: Fixes for:          ALF-12772 'Path not found' error in Share if user has no permissions to parent folders in breadcrumb          ALF-14527 Share - Error to display documents if user has no access to the parent folder          - Share now correctly supports accessing documents and folders (and details page actions) where the user does not have Read permissions on the parent node.       46101: MNT-293: AccessDenied using CMIS when user does not have access to parent folder       - Fix by Vasily       46125: MNT-293: Correct Kev's logic to do permission checks after resolving a path as system       46127: Merged V3.4 to PATCHES/V3.4.10          45743: Correction to AuditComponentTest             - Test was reporting "Incorrect number of audit entries after failed login expected:<1000> but was:<XXX>"               where XXX was less than 1000. This was because results was being cleared if all all audit failures were               not available in the first loop. The results needed to cleared before the first loop rather than in every               loop. For example an XXX value of 830 would simply indicate that the first loop had received 170 audit               results and that a second loop was required to get the rest.          45747: Correction to AuditComponentTest             - Okay last commit did not work. Try just waiting a bit longer than a second if we don't have all records.    46195: ALF-17880 / ALF-17378: Web content is not editable after cancelling the Edit Web Content Wizard    - Fix by Andrey    46227: Filter repository test resources from alfresco.war    46324: Merged DEV to V3.4-BUG-FIX (with improvements)       45602: ALF-10569 / ALF-17519 : SPP is setting residual properties with an unknown name space (urn:schemas-microsoft-com)       Implemented special case for handling dead webdav properties. New webdav:object aspect was introduced. It is used to       store all dead properties that may be set on resource.    46353: ALF-17881 / ALF-17272: TooManyClauses error due to syntax error in the query generated from UIComponentSelector    - Fixed typo in Lucene query generation introduced in r20310