Merged V3.4-BUG-FIX (3.4.13) to V4.1-BUG-FIX (4.1.4)    45745: Merge V3.4 (3.4.12) to V3.4-BUG-FIX (3.4.13)       45629: ALF-17536: Stack Specific: Can't transform pdf to jpg          - Added TRACE to log env properties using            log4j.logger.org.alfresco.util.exec.RuntimeExec=trace       45667: ALF-17536 Can't transform multi page pdf to jpg          - issue was introduced by ALF-15436 Alfresco 3.4c + Share + TIFF preview only shows the first page       45724: ALF-17533 CLONE - Created article or publication cant be viewed on WQS site          - Further change required to avoid deadlock       45743: Correction to AuditComponentTest          - Test was reporting "Incorrect number of audit entries after failed login expected:<1000> but was:<XXX>"            where XXX was less than 1000. This was because results was being cleared if all all audit failures were            not available in the first loop. The results needed to cleared before the first loop rather than in every            loop. For example an XXX value of 830 would simply indicate that the first loop had received 170 audit            results and that a second loop was required to get the rest.    45754: Merged V3.4 (3.4.12) to V3.4-BUG-FIX (3.4.13)       45747: Correction to AuditComponentTest          - Okay last commit did not work. Try just waiting a bit longer than a second if we don't have all records.    45976: Merged DEV to V3.4-BUG-FIX       45925: ALF-16992 : patch.fixAclInheritance is failing on sharedAclsThatDoNotInheritCorrectlyFromThePrimaryParent          Added a detection on cyclic loop for "inherits from" field.