Correction to AuditComponentTest    - Test was reporting "Incorrect number of audit entries after failed login expected:<1000> but was:<XXX>"      where XXX was less than 1000. This was because results was being cleared if all all audit failures were      not available in the first loop. The results needed to cleared before the first loop rather than in every      loop. For example an XXX value of 830 would simply indicate that the first loop had received 170 audit      results and that a second loop was required to get the rest.