MNT-316: Merged V3.4-BUG-FIX (3.4.13) to V3.4.12 (3.4.12.2)    46173: ALF-17806: Merged PATCHES/V3.4.10 to V3.4-BUG-FIX       46099: MNT-293: Merged V4.0-BUG-FIX to PATCHES/V3.4.10          37969: Fixes for:          ALF-12772 'Path not found' error in Share if user has no permissions to parent folders in breadcrumb          ALF-14527 Share - Error to display documents if user has no access to the parent folder          - Share now correctly supports accessing documents and folders (and details page actions) where the user does not have Read permissions on the parent node.       46101: MNT-293: AccessDenied using CMIS when user does not have access to parent folder       - Fix by Vasily       46125: MNT-293: Correct Kev's logic to do permission checks after resolving a path as system       46127: Merged V3.4 to PATCHES/V3.4.10          45743: Correction to AuditComponentTest             - Test was reporting "Incorrect number of audit entries after failed login expected:<1000> but was:<XXX>"               where XXX was less than 1000. This was because results was being cleared if all all audit failures were               not available in the first loop. The results needed to cleared before the first loop rather than in every               loop. For example an XXX value of 830 would simply indicate that the first loop had received 170 audit               results and that a second loop was required to get the rest.          45747: Correction to AuditComponentTest             - Okay last commit did not work. Try just waiting a bit longer than a second if we don't have all records.