ALF-12691: Alfresco Explorer doesn't work: java.lang.NoClassDefFoundError: org/apache/commons/lang/builder/HashCodeBuilder
Shared library for WAS was fixed. commons-lang-2.6.jar is used.