ALF-1838: Need to support relative url for WCM TinyMCE Filepicker
1) Modify create-html.jsp for supporting relative ursl.
2) Add two new const to the page:
                alfresco.constants.AVM_WEBAPP_PREFIX -- path to current WCM webApp folder.
                alfresco.constants.AVM_WEBAPP -- name of current WCM webApp folder.
3) Modify relative urls generation in following way:
                a) If current webApp is "ROOT", then remove alfresco.constants.AVM_WEBAPP_URL from url.
                b) If current webApp is not "ROOT" then remove alfresco.constants.AVM_WEBAPP_PREFIX from url.
                
NOTE: During testing we found a new bug. When we try to insert image during creating content from webForm, image is not shown(we see broken image icon).
It seems that webscript that retrieve content is broken because if we send following request:
"http://localhost:8080/alfresco/wcs/api/path/content/avm/test2--admin--preview/www/avm_webapps/ROOT/test.jpg"
we will get error in console: 
	
15:17:42,818 User:admin ERROR [extensions.webscripts.AbstractRuntime] Exception from executeScript - redirecting to status template error: 06140002 Unable to fi
nd ObjectPathReference[storeRef=avm://test2--admin--preview,path=/Company Home/www/avm_webapps/ROOT/test.jpg]
org.springframework.extensions.webscripts.WebScriptException: 06140002 Unable to find ObjectPathReference[storeRef=avm://test2--admin--preview,path=/Company Hom
e/www/avm_webapps/ROOT/test.jpg]

IMPORTANT: This new issue is reproducible before our code changes and therefore our changes isn't cause of this issue.