ALF-19046 - Fixed format() to UTC. Test failing within bamboo assuming test server is set to BST. expected:<2005-09-16T1[7:01:03.456Z]> but was:<2005-09-16T1[8:01:03.456+01:00]>