Merged PATCHES/V3.2.1 to V3.3 (RECORD ONLY)    20840: Incremented version label    20839: ALF-3691: Merged V3.3-BUG-FIX to PATCHES/V3.2.1       20307: VersionStore - minor fixes if running deprecated V1          - warn in startup log          - do not execute migration cleanup       20367: ALF-2829: Avoid reading entire result set into memory in FixNameCrcValuesPatch       20368: Work-around for ALF-2366: patch.updateDmPermissions takes too long to complete          - this patch may now be deferred until 3.4 using the sample context (DM will use old permissions and AVM new as it did in 2.2.x)          - this is only supported upgrading direct to 3.2.1.x       20370: Version Migrator (ALF-1000) - use common batch processor to enable multiple workers       20373: Version Migrator (ALF-1000) - resolve runtime conflict (w/ r20334)       20387: Version Migrator (ALF-1000) - approx x3 boost (policies ignore version2 store)       20431: Version Migrator (ALF-1000) - migrate 1st batch independently    20738:ALF-3617: Merged V3.3-BUG-FIX to PATCHES/V3.2.1       20438: ALF-479: Merged DEV/BELARUS/V3.2-2010_01_11 to DEV/V3.3-BUG-FIX          18448: ETHREEOH-4044: External Authentication Subsystem does not perform user mapping for WebDAV requests             The changes listed in the bug comments have been made (and corrected).    20728: Incremented version label    20727: ALF-3617: Merged HEAD to PATCHES/V3.2.1       20616: ALF-2265: Share 'Uber Filter' part 2          - WebScriptNTLMAuthenticationFilter detached from its superclass and renamed to WebScriptSSOAuthenticationFilter          - Now the filter simply chains to the downstream authentication filter rather than call its superclass          - This means the same filter can be used for Kerberos-protected webscripts as well as NTLM          - Wired globalAuthenticationFilter behind webscriptAuthenticationFilter in the filter chain in web.xml          - Configured webscriptAuthenticationFilter for Kerberos subsystem    20612: Incremented version label    20610: Merged V3.3 to PATCHES/V3.2.1       20590: Fixed ALF-3189: Oracle/DB2/SQLServer/PostgreSQL are missing indexes to support many FK constraints         - Reverses rev 17421         - Added patchy bits to post-create script and declared patch         - Patch only applies to *new* installations from 3.2.0 onwards (schema 3007 to 3501)    20403: Merged V3.3 to PATCHES/V3.2.1       20398: Fixed ALF-2890: Upgrade removes content if transaction retries are triggered          - Setting ContentData that was derived outside of the current transaction opened up a window for the post-rollback code to delete the underlying binary. The binaries are only registered for writers fetched via the ContentService now; the low-level DAO no longer does management because it can't assume that a new content URL indicates a new underlying binary.          - The contentUrlConverter was creating new URLs and thus the low-level DAO cleaned up live content when retrying collisions took place. The cleanup is no longer on the stack for the patch.          - Removes the ALF-558 changes around ContentData.reference()    20391: Incremented version label    20390: ALF-2966: Merged DEV/V3.3-BUG-FIX to PATCHES/V3.2.1       20388: Merged BRANCHES/DEV/BELARUS/HEAD-2010_04_28 to BRANCHES/DEV/V3.3-BUG-FIX:          20372: ALF-897: It is impossible to create content when default value selected in ContentHeadlineBackground field for intranet_rssi_landing_template web-form (also fixes ALF-2798 & ALF-791)    20371: ALF-2861: Merged V3.2 to PATCHES/V3.2.1       20028: Reverted (and fixed line endings) of log4j.properties       20027: Merged BRANCHES/V3.1 to BRANCHES/V3.2:          19983: Changes for ALF-2545: Cannot upgrade from 2.1.2a (b 209) to the 3.1.2 (.a3 458) on Oracle          20008: ALF-2351: Oracle upgrade scripts need enhancements from 2.2SP7    20362: ALF-2883: Merged HEAD to V3.2.1       19750: Fix for ALF-2310: alfresco-mmt-3.3dev.jar shows NoClassDefFoundError: org/safehaus/uuid/UUIDGenerator    20359: Merged PATCHES/V3.2.0 to PATCHES/V3.2.1       20349: Merged V3.3 to PATCHES/V3.2.0          20346: ALF-2839: Node pre-loading generates needless resultset rows             - Added missing Criteria.list() call       20280: Fixed ALF-2839: Node pre-loading generates needless resultset rows          - Split Criteria query to retrieve properties and aspects separately       20272: Backports to help fix ALF-2839: Node pre-loading generates needless resultset rows          Merged BRANCHES/V3.2 to PATCHES/V3.2.0:             18490: Added cache for alf_content_data          Merged BRANCHES/DEV/V3.3-BUG-FIX to PATCHES/V3.2.0:             20231: Fixed ALF-2784: Degradation of performance between 3.1.1 and 3.2x (observed in JSF)       20266: Test reproduction of ALF-2839 failure: Node pre-loading generates needless resultset rows    20358: Increment version label    20343: Incremented version label    20342: Merged V3.3 to PATCHES/V3.2.1       20322: Fixed ALF-1998: contentStoreCleanerJob leads to foreign key exception          - Possible concurrent modification of alf_content_url.orphan_time led to false orphan detection          - Fixed queries to check for dereferencing AND use the indexed orphan_time column          - More robust use of EagerContentStoreCleaner: On eager cleanup, ensure that URLs are deleted          - Added optimistic lock checks on updates and deletes of alf_content_url