Merged V4.1-BUG-FIX to HEAD    40937: ALF-15702, ALF-15669: mmt-dependencies was messing up the SDK classpath    40939: ALF-15696: Remove svnkit.jar - makes the build fail if the version of installed command line svn is 1.7. Using commandline binding for <svn> Ant task to be consistent with other parts of the build.    40942: ALF-15595 Pooled review workflow has a percentage parameter that has no effect. "Required Approve Percentage" removed from pooled review approve activiti form configuration as was done for ALF-8489 for jbpm form configuration.    40956: ALF-15717: Merged V4.0-BUG-FIX to V4.1-BUG-FIX (Lost revision)       33680: Merged DEV to V4.0-BUG-FIX          33675: ALF-12379: WebLogic: alfresco fails to start: java.lang.NoSuchMethodError: org.apache.commons.lang.mutable.MutableInt.increment()V             org.apache.commons.* package should be used as application's preferrable for WebLogic.    40962: ALF-15635 ALF-14738: Use the right property to write Community vs. Enterprise in war manifest files    40965: Merge Dev to V4.1-BUG_FIX      ALF-14144 : "Append failed" error message with IMAP when email contains a .msg file attached    40977: Sync parser generation    40983: Fixed: ALF-15730: MSSQL: It's impossible to upgrade Alfresco from 3.4.10 to 4.1.1 (build 134)     - Taken directly from bug investigation phase    40986: ALF-15706 Unfriendly isCloudSyncKeyAvailable button on License Descriptior page    40992: Merged BRANCHES/DEV/FEATURES/CLOUD1_SALESFORCE/ to BRANCHES/DEV/V4.1-BUG-FIX:       40988: Fixes ALF-13698: Makes sure the default submit handler doesn't trigger    40997: Fix for ALF-15718 - correctly deal with browser headers as case-insensitive during headers map lookups.    41002: Show Cloud Sync Key Available on license descriptor.    41008: ALF-15744: Another WQS lucene resultset leak    - Follow on from ALF-15505. New since 3.4.9    41010: ALF-15697: Not possible to start workflow not specifying the Due Date    - Regression caused by ALF-10243    41027: ALF-15193: "Folder Is Not a Folder CmisInvalidArgumentException thrown when using cmis:objectId"    41029: Fix for ALF-14388 - Edit Online option is not supported for '.docm', 'dotm', '.xlsm' files    41032: Fix for ALF-15753	Infinite loop during Solr ACL indexing when ACL Changeset batch is empty